# Use the official Debian image from Docker Hub
FROM dakshinatharindu/debian:latest

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive

# Install dependencies (you can modify this based on your needs)
RUN apt-get update && apt-get install -y \
    sudo \
    git \
    curl \
    vim \
    build-essential \
    python3 \
    python3-pip \
    lsb-release wget software-properties-common gnupg \
    ninja-build pkg-config libglib2.0-dev \
    xxd file cpio unzip rsync bc 
    && apt-get clean

# Install Risc-V toolchain
RUN mkdir -p /opt/riscv
RUN wget https://github.com/dakshinatharindu/dockerfiles/releases/download/rv32g/riscv.tar.gz
RUN tar -xvf riscv.tar.gz -C /opt
RUN rm riscv.tar.gz
ENV PATH="/opt/riscv/bin:${PATH}"

# Install qemu-system-riscv32
RUN apt-get install -y qemu-system-misc

# Create a new user with a home directory and set a default shell
RUN useradd -m -s /bin/bash riscv

# Give the new user sudo privileges
RUN echo 'riscv ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

# Switch to afluser and install Rust
USER riscv

# Set the working directory for the user
WORKDIR /home/riscv

# Set the default command to bash (this can be modified as needed)
CMD ["/bin/bash"]
